#!/usr/bin/env bash
# herdr-box entrypoint — runs as root, prepares persistent state, then execs sshd.
set -euo pipefail

HOME_DIR=/home/dev
HOSTKEY_DIR=/etc/ssh/hostkeys

# 1. SSH host keys persist on the volume so pod rescheduling doesn't change
#    the box's SSH identity (no host-key warnings on every reschedule).
mkdir -p "$HOSTKEY_DIR"
for type in ed25519 rsa; do
    key="$HOSTKEY_DIR/ssh_host_${type}_key"
    [ -f "$key" ] || ssh-keygen -q -t "$type" -f "$key" -N ''
done
chmod 700 "$HOSTKEY_DIR"
chmod 600 "$HOSTKEY_DIR"/ssh_host_*_key

# 2. First boot on an empty volume: seed the home directory.
if [ ! -e "$HOME_DIR/.profile" ]; then
    cp -a /etc/skel/. "$HOME_DIR/"
    chown -R dev:dev "$HOME_DIR"
fi
chown dev:dev "$HOME_DIR"

# 2b. Claude Code runs its first-run wizard (theme + an OAuth login screen)
#     unless onboarding is already marked complete — it never reaches
#     CLAUDE_CODE_OAUTH_TOKEN otherwise. Merge the flags in without touching
#     anything else the file already holds.
python3 - <<'PY'
import json, os, pathlib
p = pathlib.Path("/home/dev/.claude.json")
try:
    d = json.loads(p.read_text()) if p.exists() else {}
except ValueError:
    d = {}
if not d.get("hasCompletedOnboarding"):
    d.update({"hasCompletedOnboarding": True, "theme": "dark",
              "lastOnboardingVersion": os.environ.get("CLAUDE_CODE_VERSION", "2.1.251")})
    p.write_text(json.dumps(d, indent=2))
    os.chown(p, 1000, 1000)
    p.chmod(0o600)
PY

# 3. authorized_keys come from the mounted ConfigMap — declarative, replaced
#    on every boot. Add/remove keys in git, not on the box.
if [ -f /etc/herdr-box/authorized_keys ]; then
    install -d -m 700 -o dev -g dev "$HOME_DIR/.ssh"
    install -m 600 -o dev -g dev /etc/herdr-box/authorized_keys \
        "$HOME_DIR/.ssh/authorized_keys"
fi

# 4. Export selected container env into SSH sessions (sshd doesn't inherit
#    container env). Two paths, because neither covers every shell:
#      /etc/environment  — pam_env, so every PAM session including
#                          `ssh host 'cmd'` (non-login, non-interactive,
#                          where /etc/bash.bashrc returns early)
#      /run/herdr-box    — sourced by profile.d + bash.bashrc, covering
#                          herdr panes spawned by the server rather than PAM
#    Both live outside the PVC, so the token is never written to persistent
#    storage; both are recreated from the k8s Secret on every boot.
: > /etc/environment.herdr
for var in CLAUDE_CODE_OAUTH_TOKEN DISABLE_AUTOUPDATER; do
    [ -n "${!var:-}" ] && printf '%s=%s\n' "$var" "${!var}" >> /etc/environment.herdr
done
# Keep any distro-provided lines, then append ours.
grep -v -E '^(CLAUDE_CODE_OAUTH_TOKEN|DISABLE_AUTOUPDATER)=' /etc/environment 2>/dev/null \
    > /etc/environment.base || true
cat /etc/environment.base /etc/environment.herdr > /etc/environment
rm -f /etc/environment.base /etc/environment.herdr
chown root:dev /etc/environment
chmod 640 /etc/environment

mkdir -p /run/herdr-box
{
    echo "# generated by herdr-box-entrypoint"
    for var in CLAUDE_CODE_OAUTH_TOKEN DISABLE_AUTOUPDATER; do
        if [ -n "${!var:-}" ]; then
            printf 'export %s=%q\n' "$var" "${!var}"
        fi
    done
} > /run/herdr-box/env.sh
chown root:dev /run/herdr-box/env.sh
chmod 640 /run/herdr-box/env.sh

mkdir -p /run/sshd
exec "$@"
