#!/usr/bin/env bash
# herdr-box entrypoint — runs as root, prepares persistent state, then execs sshd.
set -euo pipefail

HOME_DIR=/home/dev
HOSTKEY_DIR=/etc/ssh/hostkeys

# 1. SSH host keys persist on the volume so pod rescheduling doesn't change
#    the box's SSH identity (no host-key warnings on every reschedule).
mkdir -p "$HOSTKEY_DIR"
for type in ed25519 rsa; do
    key="$HOSTKEY_DIR/ssh_host_${type}_key"
    [ -f "$key" ] || ssh-keygen -q -t "$type" -f "$key" -N ''
done
chmod 700 "$HOSTKEY_DIR"
chmod 600 "$HOSTKEY_DIR"/ssh_host_*_key

# 2. First boot on an empty volume: seed the home directory.
if [ ! -e "$HOME_DIR/.profile" ]; then
    cp -a /etc/skel/. "$HOME_DIR/"
    chown -R dev:dev "$HOME_DIR"
fi
chown dev:dev "$HOME_DIR"

# 3. authorized_keys come from the mounted ConfigMap — declarative, replaced
#    on every boot. Add/remove keys in git, not on the box.
if [ -f /etc/herdr-box/authorized_keys ]; then
    install -d -m 700 -o dev -g dev "$HOME_DIR/.ssh"
    install -m 600 -o dev -g dev /etc/herdr-box/authorized_keys \
        "$HOME_DIR/.ssh/authorized_keys"
fi

# 4. Export selected container env into SSH sessions (sshd doesn't inherit
#    container env). Readable by the dev user only.
mkdir -p /run/herdr-box
{
    echo "# generated by herdr-box-entrypoint"
    for var in CLAUDE_CODE_OAUTH_TOKEN DISABLE_AUTOUPDATER; do
        if [ -n "${!var:-}" ]; then
            printf 'export %s=%q\n' "$var" "${!var}"
        fi
    done
} > /run/herdr-box/env.sh
chown root:dev /run/herdr-box/env.sh
chmod 640 /run/herdr-box/env.sh

mkdir -p /run/sshd
exec "$@"
